import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
// Adjust the path if necessary
import "./globals.css";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white px-4 md:px-10`}>
        <Navbar />
        <div className="py-9">{/* Add top padding to prevent overlap */}</div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
